# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "Manager" do |manager|
      manager.vm.box= "centos/8"
      manager.vm.hostname="Manager"
      manager.vm.network "forwarded_port", guest: 80, host: 80
      manager.vm.network "private_network", ip:"192.168.100.100"
      manager.vm.provider"virtualbox" do |vb|
      vb.name = "Manager"
          vb.memory="1024"
          vb.cpus="2"
      end
      manager.vm.provision "file", source: "./manager_archivos", destination: "~/"

      manager.vm.provision "shell", inline: <<-SHELL
        sudo su
        mv /home/vagrant/manager_archivos/servicio /usr/bin
        chmod +x /usr/bin/servicio
        dnf install dos2unix -y
        dos2unix /usr/bin/servicio
        dnf remove dos2unix -y
        dnf install nano -y
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        dnf list docker-ce
        dnf install docker-ce  --nobest -y
        systemctl start docker | systemctl enable docker
        docker swarm init --advertise-addr 192.168.100.100

      SHELL

      
  end 

  config.vm.define "Worker1" do |worker1|
      worker1.vm.box= "centos/8"
      worker1.vm.hostname="Worker1"
      worker1.vm.network "private_network", ip:"192.168.100.101"
      worker1.vm.provider"virtualbox" do |vb|
      vb.name = "Worker1"
          vb.memory="1024"
          vb.cpus="1"
      end
      worker1.vm.provision "file", source: "./.vagrant/machines/Manager/virtualbox/private_key", destination: "~/"
      worker1.vm.provision "shell", inline: <<-SHELL
        sudo su
        dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
        dnf list docker-ce
        dnf install docker-ce  --nobest -y
        systemctl start docker | systemctl enable docker
        chmod 400 private_key
        exec $(ssh -i private_key -o StrictHostKeyChecking=no -p 22 vagrant@192.168.100.100 "sudo docker swarm join-token manager | tail -2" | tail -2)
        rm private_key
      SHELL

 end 

  config.vm.define "Worker2" do |worker2|
      worker2.vm.box= "centos/8"
      worker2.vm.hostname="Worker2"
      worker2.vm.network "private_network", ip:"192.168.100.102"
      worker2.vm.provider"virtualbox" do |vb|
      vb.name = "Worker2"
          vb.memory="1024"
          vb.cpus="1"
      end
     worker2.vm.provision "file", source: "./.vagrant/machines/Manager/virtualbox/private_key", destination: "~/"
     worker2.vm.provision "shell", inline: <<-SHELL
       sudo su
       dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
       dnf list docker-ce
       dnf install docker-ce  --nobest -y
       systemctl start docker | systemctl enable docker
       chmod 400 private_key
       exec $(ssh -i private_key -o StrictHostKeyChecking=no -p 22 vagrant@192.168.100.100 "sudo docker swarm join-token manager | tail -2" | tail -2)
       rm private_key
      SHELL
  end  
end